### ISSUE TITLE
[Error] Channel flow demo

### ISSUE THREAD

**Issue by akasharidas** [google/jax-cfd#136]
I'm trying to run `channel_flow_demo.ipynb`, but I get the following error when I call the `step_fn` :

(massive traceback truncated)
> [/usr/local/lib/python3.7/dist-packages/jax_cfd/base/advection.py](https://localhost:8080/#) in <genexpr>(.0)
>     107                     for u, target_offset in zip(v, target_offsets))
>     108   aligned_c = tuple(c_interpolation_fn(c, target_offset, aligned_v, dt)
> --> 109                     for target_offset in target_offsets)
>     110   return _advect_aligned(aligned_c, aligned_v)
>     111 
> 
> [/usr/local/lib/python3.7/dist-packages/jax_cfd/base/interpolation.py](https://localhost:8080/#) in tvd_interpolation(c, offset, v, dt)
>     282         c_left = c.shift(-1, axis)
>     283         c_right = c.shift(1, axis)
> --> 284         c_next_right = c.shift(2, axis)
>     285         # Velocities of different sign are evaluated with limiters at different
>     286         # points. See equations (4.34) -- (4.39) from the reference above.
> 
> [/usr/local/lib/python3.7/dist-packages/jax_cfd/base/grids.py](https://localhost:8080/#) in shift(self, offset, axis)
>     269       GridArray has offset `u.offset + offset`.
>     270     """
> --> 271     return self.bc.shift(self.array, offset, axis)
>     272 
>     273   def _interior_grid(self) -> Grid:
> 
> [/usr/local/lib/python3.7/dist-packages/jax_cfd/base/boundaries.py](https://localhost:8080/#) in shift(self, u, offset, axis)
>      77       `u.offset + offset`.
>      78     """
> ---> 79     padded = self._pad(u, offset, axis)
>      80     trimmed = self._trim(padded, -offset, axis)
>      81     return trimmed
> 
> [/usr/local/lib/python3.7/dist-packages/jax_cfd/base/boundaries.py](https://localhost:8080/#) in _pad(self, u, width, axis)
>     116     if bc_type != BCType.PERIODIC and abs(width) > 1:
>     117       raise ValueError(
> --> 118           'Padding past 1 ghost cell is not defined in nonperiodic case.')
>     119 
>     120     if bc_type == BCType.PERIODIC:
> 
> ValueError: Padding past 1 ghost cell is not defined in nonperiodic case.

I installed JAX-CFD on a fresh Colab notebook using `pip install git+https://github.com/google/jax-cfd.git`

Please help me fix this. Let me know if I'm using the wrong version (since the repo is constantly being developed).

Thanks!

**Comment by RSuryaNarayan** [comment]
I also get this error before reaching there: 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-a2a3756c4bf3>](https://localhost:8080/#) in <module>()
      9 
     10 # Specify periodic BC on x-boundaries, and no-slip walls on the y-boundaries.
---> 11 velocity_bc = (cfd.boundaries.periodic_and_dirichlet_boundary_conditions(),
     12                cfd.boundaries.periodic_and_dirichlet_boundary_conditions())
     13 

AttributeError: module 'jax_cfd.base' has no attribute 'boundaries'
```
used a simple ```pip install jax-cfd``` in the fresh notebook.

**Comment by juliandwain** [comment]
I get the same error as @akasharidas.

**Comment by RSuryaNarayan** [comment]
Never mind the error above, I installed jax from scratch and ran it from a local jupyter notebook, it worked. Stuck at the same point as @akasharidas

**Comment by shoyer** [comment]
You need to install the development version of JAX-CFD, e.g., `pip install -U git+https://github.com/google/jax-cfd.git`

I will see about making a new release so installing from PyPI works!

**Comment by juliandwain** [comment]
Thank you for your answer @shoyer !

Unfortunately, I still get the same error after creating a new conda environment (Python 3.9.11) and installing JAX-CFD the way you suggested:

```properties

File ~/miniconda3/envs/data_gen/lib/python3.9/site-packages/jax_cfd/base/boundaries.py:117, in ConstantBoundaryConditions._pad(self, u, width, axis)
    [114](file:///home/julian/miniconda3/envs/data_gen/lib/python3.9/site-packages/jax_cfd/base/boundaries.py?line=113) offset[axis] -= padding[0]
    [116](file:///home/julian/miniconda3/envs/data_gen/lib/python3.9/site-packages/jax_cfd/base/boundaries.py?line=115) if bc_type != BCType.PERIODIC and abs(width) > 1:
--> [117](file:///home/julian/miniconda3/envs/data_gen/lib/python3.9/site-packages/jax_cfd/base/boundaries.py?line=116)   raise ValueError(
    [118](file:///home/julian/miniconda3/envs/data_gen/lib/python3.9/site-packages/jax_cfd/base/boundaries.py?line=117)       'Padding past 1 ghost cell is not defined in nonperiodic case.')
    [120](file:///home/julian/miniconda3/envs/data_gen/lib/python3.9/site-packages/jax_cfd/base/boundaries.py?line=119) if bc_type == BCType.PERIODIC:
    [121](file:///home/julian/miniconda3/envs/data_gen/lib/python3.9/site-packages/jax_cfd/base/boundaries.py?line=120)   # self.values are ignored here
    [122](file:///home/julian/miniconda3/envs/data_gen/lib/python3.9/site-packages/jax_cfd/base/boundaries.py?line=121)   pad_kwargs = dict(mode='wrap')

ValueError: Padding past 1 ghost cell is not defined in nonperiodic case.
```

**Comment by akasharidas** [comment]
> I installed JAX-CFD on a fresh Colab notebook using `pip install git+https://github.com/google/jax-cfd.git`

@shoyer I installed JAX-CFD as you suggested, and still run into the same problem.

**Comment by juliandwain** [comment]
It works for me now if I am uninstalling JAX-CFD via
```
pip uninstall jax-cfd
```
and reinstalling it via
```
pip install -U git+https://github.com/google/jax-cfd.git
```

If you do not want to wait on the new PyPI release. :)

Thank you for fixing this!
