### ISSUE TITLE
Tequila supports Cirq

### ISSUE THREAD

**Issue by westurner** [google/jax-cfd#148]
https://github.com/tequilahub/tequila#quantumchemistry

**Comment by shoyer** [comment]
Did you mean to post this in the Cirq repository instead?

**Comment by westurner** [comment]
Nope, thought I'd mention the QC chemistry part of the problem.

**Comment by westurner** [comment]
TIL about Superfluidity and Quantum Qravity w/ Bernoulli's. https://news.ycombinator.com/item?id=31383784

OT. Anyway, cool work
